### ISSUE TITLE
BackupBot crashes just sitting idle

### ISSUE THREAD

**Issue by VoderWolf** [VoderWolf/VoderBot#5]
bot blows up sitting, no command run!
![image](https://user-images.githubusercontent.com/59423520/132069124-1ce23998-d44b-447f-9294-b035dcf9ad55.png)

**Comment by hamilton1977** [comment]
after 30 secs the bot loads up the jobpool.js

issue here looks like i have a hidden or mission  deceleration of masterlist. which i did move. 

masterlist is part the "stop" restore request..

I'll fix this on a bug branch.

**Comment by hamilton1977** [comment]
Appears to be a done issue. :)
